### PR TITLE
add note about oracle installation

### PR DESCRIPTION
**Pull request by alexthomasTG**

### CODE REVIEW

**Review by lennessyy — APPROVED** [review]
Can we confirm that these steps also apply to 3.5? If so, we should propagate the changes to 3.5

**Comment by a-m-thomas** [comment]
> Can we confirm that these steps also apply to 3.5? If so, we should propagate the changes to 3.5

Good point, I've asked Limin to review this.

**Comment by LiminWangCS** [comment]
tested with 3.5.0 on OEL8, the install process also applies to it.

**Comment by a-m-thomas** [comment]
cherry-picked to 3.5

**Pull request merged**
